on:
  push:
    branches:
      - 'main'
      - 'dev'
name: Sync / sync-repo-to-gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/easydu2002
        dst: gitee/
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: 'chat_gpt_oicq'
        force_update: true
